Updated husky's pre-commit script.

diff --git a/queryon-admin/.husky/pre-commit b/queryon-admin/.husky/pre-commit
--- a/queryon-admin/.husky/pre-commit
+++ b/queryon-admin/.husky/pre-commit
@@ -1,20 +1,22 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/\_/husky.sh"
+
+# Exit immediately if any command fails
+set -e
 
 echo "Running lint-staged..."
 npx lint-staged
 
 if [ $? -ne 0 ]; then
-echo "Lint-staged failed. Aborting commit."
-exit 1
+  echo "Lint-staged failed. Aborting commit."
+  exit 1
 fi
 
 echo "Running build..."
 npm run build
 
 if [ $? -ne 0 ]; then
-echo "Build failed. Aborting commit."
-exit 1
+  echo "Build failed. Aborting commit."
+  exit 1
 fi
 
 echo "Pre-commit hook completed successfully."
